# Use root/example as user/password credentials
version: '3.1'

services:

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet


  udm:
    build: .
    ports:
      - 8080:8080
    links:
      - mongodb
    depends_on:
      - mongodb