# Use root/example as user/password credentials
version: '3.1'

services:
  db01:
    image: mongo
    volumes:
      - datadb01:/data/db
      - ./mongod.conf:/etc/mongod.conf
    command: mongod --smallfiles
    container_name: db01

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - 8081:8080

  udm:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db01
      - client

volumes:
  datadb01:
  datadb02:

