openapi: 3.0.0

info:
  version: '1.0.0'
  title: 'Nudm_SDM'
  description: 'Nudm Subscriber Data Management Service'

externalDocs:
  description: 3GPP TS 29.503 Unified Data Management Services, version 15.2.0
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.503/'

servers:
  - url: '{apiRoot}/nudm-sdm/v1'
    variables:
      apiRoot:
        default: http://localhost:8080
        description: apiRoot as defined in subclause subclause 4.4 of 3GPP TS 29.501.

#security:
#  - oAuth2ClientCredentials:
#    - nudm-sdm
#  - {}

paths:
  /{supi}:
    get:
      summary: retrieve multiple data sets
      operationId: app.getSupiById
      tags:
        - Retrieval of multiple data sets
      parameters:
        - name: supi
          in: path
          description: Identifier of the UE
          required: true
          schema:
            $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/Supi'
        - name: dataset_names
          in: query
          explode: false
          description: List of dataset names
          required: true
          schema:
             $ref: '#/components/schemas/DatasetNames'
        - name: plmn-id
          in: query
          description: serving PLMN ID
          content:
            application/json:
              schema:
                $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/PlmnId'
        - name: supported-features
          in: query
          description: Supported Features
          schema:
             $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
        - name: If-None-Match
          in: header
          description: Validator for conditional requests, as described in RFC 7232, 3.2
          schema:
            type: string
        - name: If-Modified-Since
          in: header
          description: Validator for conditional requests, as described in RFC 7232, 3.3
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionDataSets'
          headers:
            Cache-Control:
              description: Cache-Control containing max-age, as described in RFC 7234, 5.2
              schema:
                type: string
            ETag:
              description: Entity Tag, containing a strong validator, as described in RFC 7232, 2.3
              schema:
                type: string
            Last-Modified:
              description: Timestamp for last modification of the resource, as described in RFC 7232, 2.2
              schema:
                type: string
        '400':
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/responses/400'
        '404':
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/responses/404'
        '500':
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/responses/503'
        default:
          description: Unexpected error
  /{supi}/nssai:
    get:
      summary: retrieve a UE's subscribed NSSAI
      operationId: app.getSupiNssai
      tags:
        - Slice Selection Subscription Data Retrieval
      parameters:
        - name: supi
          in: path
          description: Identifier of the UE
          required: true
          schema:
            $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/Supi'
        - name: supported-features
          in: query
          description: Supported Features
          schema:
             $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
        - name: plmn-id
          in: query
          description: serving PLMN ID
          content:
            application/json:
              schema:
                $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/PlmnId'
        - name: If-None-Match
          in: header
          description: Validator for conditional requests, as described in RFC 7232, 3.2
          schema:
            type: string
        - name: If-Modified-Since
          in: header
          description: Validator for conditional requests, as described in RFC 7232, 3.3
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Nssai'
          headers:
            Cache-Control:
              description: Cache-Control containing max-age, as described in RFC 7234, 5.2
              schema:
                type: string
            ETag:
              description: Entity Tag, containing a strong validator, as described in RFC 7232, 2.3
              schema:
                type: string
            Last-Modified:
              description: Timestamp for last modification of the resource, as described in RFC 7232, 2.2
              schema:
                type: string
        '400':
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/responses/400'
        '404':
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/responses/404'
        '500':
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/responses/503'
        default:
          description: Unexpected error
  /{supi}/am-data:
    get:
      summary: retrieve a UE's Access and Mobility Subscription Data
      operationId: app.getSupiAmData
      tags:
        - Access and Mobility Subscription Data Retrieval
      parameters:
        - name: supi
          in: path
          description: Identifier of the UE
          required: true
          schema:
            $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/Supi'
        - name: supported-features
          in: query
          description: Supported Features
          schema:
             $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
        - name: plmn-id
          in: query
          description: serving PLMN ID
          content:
            application/json:
              schema:
                $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/PlmnId'
        - name: If-None-Match
          in: header
          description: Validator for conditional requests, as described in RFC 7232, 3.2
          schema:
            type: string
        - name: If-Modified-Since
          in: header
          description: Validator for conditional requests, as described in RFC 7232, 3.3
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessAndMobilitySubscriptionData'
          headers:
            Cache-Control:
              description: Cache-Control containing max-age, as described in RFC 7234, 5.2
              schema:
                type: string
            ETag:
              description: Entity Tag, containing a strong validator, as described in RFC 7232, 2.3
              schema:
                type: string
            Last-Modified:
              description: Timestamp for last modification of the resource, as described in RFC 7232, 2.2
              schema:
                type: string
        '400':
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/responses/400'
        '404':
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/responses/404'
        '500':
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/responses/503'
        default:
          description: Unexpected error
  /{supi}/sdm-subscriptions:
    post:
      summary: subscribe to notifications
      operationId: app.postSupiSdmSubscriptions
      tags:
        - Subscription Creation
      parameters:
        - name: supi
          in: path
          description: SUPI of the user
          required: true
          schema:
            $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/Supi'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SdmSubscription'
        required: true
      responses:
        '201':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SdmSubscription'
          headers:
            Location:
              description: 'Contains the URI of the newly created resource, according to the structure: {apiRoot}/nudm-sdm/v1/{supi}/sdm-subscriptions/{subscriptionId}'
              required: true
              schema:
                type: string
        '400':
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/responses/400'
        '404':
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/responses/404'
        '500':
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/responses/500'
        '501':
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/responses/501'
        '503':
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/responses/503'
        default:
          description: Unexpected error
      callbacks:
        datachangeNotification:
          '{request.body#/callbackReference}':
            post:
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/ModificationNotification'
              responses:
                '204':
                  description: Successful Notification response
                '307':
                  description: Temporary Redirect
                  content:
                    application/problem+json:
                      schema:
                        $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
                '308':
                  description: Permanent Redirect
                  content:
                    application/problem+json:
                      schema:
                        $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
                '400':
                  $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/responses/400'
                '404':
                  $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/responses/404'
                '500':
                  $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/responses/500'
                '503':
                  $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/responses/503'
                default:
                  description: Unexpected error
  /{supi}/sdm-subscriptions/{subscriptionId}:
    delete:
      summary: unsubscribe from notifications
      operationId: app.deleteSupiSubscriptionById
      tags:
        - Subscription Deletion
      parameters:
        - name: supi
          in: path
          description: SUPI of the user
          required: true
          schema:
            $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/Supi'
        - name: subscriptionId
          in: path
          description: Id of the SDM Subscription
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Successful response
        '400':
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/responses/400'
        '500':
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/responses/503'
        default:
          description: Unexpected error

components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{nrfApiRoot}/oauth2/token'
          scopes:
            nudm-sdm: Access to the nudm-sdm API

  schemas:

# COMPLEX TYPES:

    DatasetNames:
      type: array
      items:
        $ref: '#/components/schemas/DataSetName'
      minItems: 2
      uniqueItems: true

    SubscriptionDataSets:
      type: object
      properties:
        amData:
          $ref: '#/components/schemas/AccessAndMobilitySubscriptionData'
        uecSmfData:
          $ref: '#/components/schemas/UeContextInSmfData'

    AccessAndMobilitySubscriptionData:
      type: object
      properties:
        supportedFeatures:
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
        subscribedUeAmbr:
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/AmbrRm'
        nssai:
          $ref: '#/components/schemas/Nssai'
        ratRestrictions:
          type: array
          items:
            $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/RatType'
        forbiddenAreas:
          type: array
          items:
            $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/Area'
        serviceAreaRestriction:
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/ServiceAreaRestriction'
        coreNetworkTypeRestrictions:
          type: array
          items:
            $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/CoreNetworkType'

    Nssai:
      type: object
      required:
       - defaultSingleNssais
      properties:
        supportedFeatures:
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
        defaultSingleNssais:
          type: array
          items:
            $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/Snssai'
          minItems: 1
        singleNssais:
          type: array
          items:
            $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/Snssai'
          minItems: 1
      nullable: true

    UeContextInSmfData:
      type: object
      properties:
        pduSessions:
          description: A map (list of key-value pairs where PduSessionId serves as key) of PduSessions
          type: object
          additionalProperties:
            $ref: '#/components/schemas/PduSession'
        pgwInfo:
          type: array
          items:
            $ref: '#/components/schemas/PgwInfo'
          minItems: 1

    PduSession:
      type: object
      required:
        - dnn
        - smfInstanceId
        - plmnId
      properties:
        dnn:
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/Dnn'
        smfInstanceId:
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/NfInstanceId'
        plmnId:
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/PlmnId'

    PgwInfo:
      type: object
      required:
        - dnn
        - pgwFqdn
      properties:
        dnn:
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/Dnn'
        pgwFqdn:
          type: string
        plmnId:
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/PlmnId'

    SdmSubscription:
      type: object
      required:
        - nfInstanceId
        - callbackUri
        - monitoredResourceUri
      properties:
        nfInstanceId:
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/NfInstanceId'
        implicitUnsubscribe:
          type: boolean
        expires:
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/DateTime'
        amfServiceName:
          $ref: '#/components/schemas/ServiceName'
        callbackUri:
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/Uri'
        monitoredResourceUri:
          type: array
          items:
            $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/Uri'
          minItems: 1
        singleNssai:
          $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/Snssai'

    ModificationNotification:
      type: object
      required:
        - notifyItems
      properties:
        notifyItems:
          type: array
          items:
            $ref: 'file:///openapi/TS29571_CommonData.yaml#/components/schemas/NotifyItem'
          minItems: 1

# SIMPLE TYPES:
    ServiceName:
      type: string

# ENUMS:

    DataSetName:
      type: string
