openapi: 3.0.0

info:
  version: '1.0.0'
  title: 'Nudm_UECM'
  description: 'Nudm Context Management Service'

externalDocs:
  description: 3GPP TS 29.503 Unified Data Management Services, version 15.2.0
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.503/'

servers:
  - url: '{apiRoot}/nudm-uecm/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in subclause subclause 4.4 of 3GPP TS 29.501.

security:
  - oAuth2ClientCredentials:
    - nudm-uecm
  - {}

paths:
  /{ueId}/registrations/amf-non-3gpp-access:
    put:
      summary: register as AMF for non-3GPP access
      operationId: app.putRegistrationAmfNon3gppAccess
      tags:
        - AMF registration for non-3GPP access
      parameters:
        - name: ueId
          in: path
          description: Identifier of the UE
          required: true
          schema:
            $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/schemas/Supi'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AmfNon3GppAccessRegistration'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AmfNon3GppAccessRegistration'
          headers:
            Location:
              description: 'Contains the URI of the newly created resource, according to the structure: {apiRoot}/nudm-uecm/v1/{ueId}/registrations/amf-non-3gpp-access'
              required: true
              schema:
                type: string
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AmfNon3GppAccessRegistration'
        '204':
          description: No Content
        '400':
          $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/responses/400'
        '403':
          $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/responses/404'
        '500':
          $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/responses/503'
        default:
          description: Unexpected error
    patch:
      summary: update a parameter in the AMF registration for non-3GPP access
      operationId: app.patchRegistrationAmfNon3gppAccess
      tags:
        - Parameter update in the AMF registration for non-3GPP access
      parameters:
        - name: ueId
          in: path
          description: Identifier of the UE
          required: true
          schema:
            $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/schemas/Supi'
      requestBody:
        content:
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/AmfNon3GppAccessRegistrationModification'
        required: true
      responses:
        '204':
          description: Expected response to a valid request
        '400':
          $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/responses/400'
        '404':
          $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/responses/404'
        '422':
          description: Unprocessable Request
          content:
            application/problem+json:
              schema:
                $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
        '500':
          $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/responses/503'
        default:
          description: Unexpected error
    get:
      summary: retrieve the AMF registration for non-3GPP access information
      operationId: app.getRegistrationAmfNon3gppAccess
      tags:
        - AMF non-3GPP-access Registration Info  Retrieval
      parameters:
        - name: ueId
          in: path
          description: Identifier of the UE
          required: true
          schema:
            $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/schemas/Gpsi'
        - name: supported-features
          in: query
          schema:
            $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AmfNon3GppAccessRegistration'
        '400':
          $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/responses/400'
        '403':
          $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/responses/404'
        '500':
          $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/responses/503'
        default:
          description: Unexpected error

components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{nrfApiRoot}/oauth2/token'
          scopes:
            nudm-uecm: Access to the nudm-uecm API

  schemas:

# COMPLEX TYPES:

    AmfNon3GppAccessRegistration:
      type: object
      required:
        - amfInstanceId
        - imsVoPs
        - deregCallbackUri
        - guami
        - ratType
      properties:
        amfInstanceId:
          $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/schemas/NfInstanceId'
        supportedFeatures:
          $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
        purgeFlag:
          $ref: '#/components/schemas/PurgeFlag'
        pei:
          $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/schemas/Pei'
        imsVoPs:
          $ref: '#/components/schemas/ImsVoPs'
        deregCallbackUri:
          $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/schemas/Uri'
        guami:
          $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/schemas/Guami'
        backupAmfInfo:
          type: array
          items:
            $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/schemas/BackupAmfInfo'
          minItems: 1
        ratType:
          $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/schemas/RatType'


    AmfNon3GppAccessRegistrationModification:
      type: object
      required:
        - guami
      properties:
        guami:
          $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/schemas/Guami'
        purgeFlag:
          $ref: '#/components/schemas/PurgeFlag'
        pei:
          $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/schemas/Pei'
        backupAmfInfo:
          type: array
          items:
            $ref: 'file:///home/dschrimpsher/PycharmProjects/converged-core-udm/udm_api/openapi/TS29571_CommonData.yaml#/components/schemas/BackupAmfInfo'

# SIMPLE TYPES:

    PurgeFlag:
      type: boolean

# ENUMS:

    ImsVoPs:
      anyOf:
        - type: string
          enum:
          - HOMOGENEOUS_SUPPORT
          - HOMOGENEOUS_NON_SUPPORT
          - NON_HOMOGENEOUS_OR_UNKNOWN
        - type: string
